name: Update 2.x OAS definitions
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * 0'
jobs:
  update-definitions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update tools
        run: curl https://raw.githubusercontent.com/tuutti/tools/main/openapi-generator/base.mk > tools/base.mk

      - name: Update definitions
        run: make

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          committer: GitHub <noreply@github.com>
          author: actions-bot <actions-bot@users.noreply.github.com>
          commit-message: Update client
          title: Update definitions
          branch: update-definitions-2.x
